/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingVerificationRouteImport } from './routes/onboarding.verification'
import { Route as OnboardingLockedRouteImport } from './routes/onboarding.locked'
import { Route as OnboardingLanguageRouteImport } from './routes/onboarding.language'
import { Route as IssuesNewRouteImport } from './routes/issues.new'
import { Route as IssuesStatusIssueIdRouteImport } from './routes/issues.status.$issueId'
import { Route as IssuesEditIssueIdRouteImport } from './routes/issues.edit.$issueId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IssuesRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingVerificationRoute = OnboardingVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLockedRoute = OnboardingLockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLanguageRoute = OnboardingLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => OnboardingRoute,
} as any)
const IssuesNewRoute = IssuesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IssuesRoute,
} as any)
const IssuesStatusIssueIdRoute = IssuesStatusIssueIdRouteImport.update({
  id: '/status/$issueId',
  path: '/status/$issueId',
  getParentRoute: () => IssuesRoute,
} as any)
const IssuesEditIssueIdRoute = IssuesEditIssueIdRouteImport.update({
  id: '/edit/$issueId',
  path: '/edit/$issueId',
  getParentRoute: () => IssuesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/home': typeof HomeRoute
  '/issues': typeof IssuesRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/settings': typeof SettingsRoute
  '/issues/new': typeof IssuesNewRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/locked': typeof OnboardingLockedRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/issues/': typeof IssuesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/issues/edit/$issueId': typeof IssuesEditIssueIdRoute
  '/issues/status/$issueId': typeof IssuesStatusIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/home': typeof HomeRoute
  '/settings': typeof SettingsRoute
  '/issues/new': typeof IssuesNewRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/locked': typeof OnboardingLockedRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/issues': typeof IssuesIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/issues/edit/$issueId': typeof IssuesEditIssueIdRoute
  '/issues/status/$issueId': typeof IssuesStatusIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/home': typeof HomeRoute
  '/issues': typeof IssuesRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/settings': typeof SettingsRoute
  '/issues/new': typeof IssuesNewRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/locked': typeof OnboardingLockedRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/issues/': typeof IssuesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/issues/edit/$issueId': typeof IssuesEditIssueIdRoute
  '/issues/status/$issueId': typeof IssuesStatusIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/home'
    | '/issues'
    | '/onboarding'
    | '/settings'
    | '/issues/new'
    | '/onboarding/language'
    | '/onboarding/locked'
    | '/onboarding/verification'
    | '/onboarding/welcome'
    | '/issues/'
    | '/onboarding/'
    | '/issues/edit/$issueId'
    | '/issues/status/$issueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/home'
    | '/settings'
    | '/issues/new'
    | '/onboarding/language'
    | '/onboarding/locked'
    | '/onboarding/verification'
    | '/onboarding/welcome'
    | '/issues'
    | '/onboarding'
    | '/issues/edit/$issueId'
    | '/issues/status/$issueId'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/home'
    | '/issues'
    | '/onboarding'
    | '/settings'
    | '/issues/new'
    | '/onboarding/language'
    | '/onboarding/locked'
    | '/onboarding/verification'
    | '/onboarding/welcome'
    | '/issues/'
    | '/onboarding/'
    | '/issues/edit/$issueId'
    | '/issues/status/$issueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  HomeRoute: typeof HomeRoute
  IssuesRoute: typeof IssuesRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/issues/': {
      id: '/issues/'
      path: '/'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/verification': {
      id: '/onboarding/verification'
      path: '/verification'
      fullPath: '/onboarding/verification'
      preLoaderRoute: typeof OnboardingVerificationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/locked': {
      id: '/onboarding/locked'
      path: '/locked'
      fullPath: '/onboarding/locked'
      preLoaderRoute: typeof OnboardingLockedRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/language': {
      id: '/onboarding/language'
      path: '/language'
      fullPath: '/onboarding/language'
      preLoaderRoute: typeof OnboardingLanguageRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/issues/new': {
      id: '/issues/new'
      path: '/new'
      fullPath: '/issues/new'
      preLoaderRoute: typeof IssuesNewRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/issues/status/$issueId': {
      id: '/issues/status/$issueId'
      path: '/status/$issueId'
      fullPath: '/issues/status/$issueId'
      preLoaderRoute: typeof IssuesStatusIssueIdRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/issues/edit/$issueId': {
      id: '/issues/edit/$issueId'
      path: '/edit/$issueId'
      fullPath: '/issues/edit/$issueId'
      preLoaderRoute: typeof IssuesEditIssueIdRouteImport
      parentRoute: typeof IssuesRoute
    }
  }
}

interface IssuesRouteChildren {
  IssuesNewRoute: typeof IssuesNewRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  IssuesEditIssueIdRoute: typeof IssuesEditIssueIdRoute
  IssuesStatusIssueIdRoute: typeof IssuesStatusIssueIdRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesNewRoute: IssuesNewRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  IssuesEditIssueIdRoute: IssuesEditIssueIdRoute,
  IssuesStatusIssueIdRoute: IssuesStatusIssueIdRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

interface OnboardingRouteChildren {
  OnboardingLanguageRoute: typeof OnboardingLanguageRoute
  OnboardingLockedRoute: typeof OnboardingLockedRoute
  OnboardingVerificationRoute: typeof OnboardingVerificationRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingLanguageRoute: OnboardingLanguageRoute,
  OnboardingLockedRoute: OnboardingLockedRoute,
  OnboardingVerificationRoute: OnboardingVerificationRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  HomeRoute: HomeRoute,
  IssuesRoute: IssuesRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
