/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingVerificationRouteImport } from './routes/onboarding.verification'
import { Route as OnboardingLockedRouteImport } from './routes/onboarding.locked'
import { Route as IssuesNewRouteImport } from './routes/issues_.new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingVerificationRoute = OnboardingVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLockedRoute = OnboardingLockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => OnboardingRoute,
} as any)
const IssuesNewRoute = IssuesNewRouteImport.update({
  id: '/issues_/new',
  path: '/issues/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/home': typeof HomeRoute
  '/issues': typeof IssuesRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/settings': typeof SettingsRoute
  '/issues/new': typeof IssuesNewRoute
  '/onboarding/locked': typeof OnboardingLockedRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/home': typeof HomeRoute
  '/issues': typeof IssuesRoute
  '/settings': typeof SettingsRoute
  '/issues/new': typeof IssuesNewRoute
  '/onboarding/locked': typeof OnboardingLockedRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/home': typeof HomeRoute
  '/issues': typeof IssuesRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/settings': typeof SettingsRoute
  '/issues_/new': typeof IssuesNewRoute
  '/onboarding/locked': typeof OnboardingLockedRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/home'
    | '/issues'
    | '/onboarding'
    | '/settings'
    | '/issues/new'
    | '/onboarding/locked'
    | '/onboarding/verification'
    | '/onboarding/welcome'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/home'
    | '/issues'
    | '/settings'
    | '/issues/new'
    | '/onboarding/locked'
    | '/onboarding/verification'
    | '/onboarding/welcome'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/home'
    | '/issues'
    | '/onboarding'
    | '/settings'
    | '/issues_/new'
    | '/onboarding/locked'
    | '/onboarding/verification'
    | '/onboarding/welcome'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  HomeRoute: typeof HomeRoute
  IssuesRoute: typeof IssuesRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  IssuesNewRoute: typeof IssuesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/verification': {
      id: '/onboarding/verification'
      path: '/verification'
      fullPath: '/onboarding/verification'
      preLoaderRoute: typeof OnboardingVerificationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/locked': {
      id: '/onboarding/locked'
      path: '/locked'
      fullPath: '/onboarding/locked'
      preLoaderRoute: typeof OnboardingLockedRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/issues_/new': {
      id: '/issues_/new'
      path: '/issues/new'
      fullPath: '/issues/new'
      preLoaderRoute: typeof IssuesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingLockedRoute: typeof OnboardingLockedRoute
  OnboardingVerificationRoute: typeof OnboardingVerificationRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingLockedRoute: OnboardingLockedRoute,
  OnboardingVerificationRoute: OnboardingVerificationRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  HomeRoute: HomeRoute,
  IssuesRoute: IssuesRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SettingsRoute: SettingsRoute,
  IssuesNewRoute: IssuesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
