/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as PostsNewRouteImport } from './routes/posts.new'
import { Route as OnboardingVerificationRouteImport } from './routes/onboarding.verification'
import { Route as OnboardingRegistrationRouteImport } from './routes/onboarding.registration'
import { Route as OnboardingLockedRouteImport } from './routes/onboarding.locked'
import { Route as OnboardingLanguageRouteImport } from './routes/onboarding.language'
import { Route as OnboardingAuthMethodRouteImport } from './routes/onboarding.auth-method'
import { Route as IssuesNewRouteImport } from './routes/issues.new'
import { Route as PostsEditPostIdRouteImport } from './routes/posts.edit.$postId'
import { Route as PostsPostIdCommentsRouteImport } from './routes/posts.$postId.comments'
import { Route as IssuesStatusIssueIdRouteImport } from './routes/issues.status.$issueId'
import { Route as IssuesEditIssueIdRouteImport } from './routes/issues.edit.$issueId'
import { Route as IssuesIssueIdCommentsRouteImport } from './routes/issues.$issueId.comments'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IssuesRoute,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PostsRoute,
} as any)
const OnboardingVerificationRoute = OnboardingVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRegistrationRoute = OnboardingRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLockedRoute = OnboardingLockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLanguageRoute = OnboardingLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAuthMethodRoute = OnboardingAuthMethodRouteImport.update({
  id: '/auth-method',
  path: '/auth-method',
  getParentRoute: () => OnboardingRoute,
} as any)
const IssuesNewRoute = IssuesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IssuesRoute,
} as any)
const PostsEditPostIdRoute = PostsEditPostIdRouteImport.update({
  id: '/edit/$postId',
  path: '/edit/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const PostsPostIdCommentsRoute = PostsPostIdCommentsRouteImport.update({
  id: '/$postId/comments',
  path: '/$postId/comments',
  getParentRoute: () => PostsRoute,
} as any)
const IssuesStatusIssueIdRoute = IssuesStatusIssueIdRouteImport.update({
  id: '/status/$issueId',
  path: '/status/$issueId',
  getParentRoute: () => IssuesRoute,
} as any)
const IssuesEditIssueIdRoute = IssuesEditIssueIdRouteImport.update({
  id: '/edit/$issueId',
  path: '/edit/$issueId',
  getParentRoute: () => IssuesRoute,
} as any)
const IssuesIssueIdCommentsRoute = IssuesIssueIdCommentsRouteImport.update({
  id: '/$issueId/comments',
  path: '/$issueId/comments',
  getParentRoute: () => IssuesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/issues': typeof IssuesRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/issues/new': typeof IssuesNewRoute
  '/onboarding/auth-method': typeof OnboardingAuthMethodRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/locked': typeof OnboardingLockedRoute
  '/onboarding/registration': typeof OnboardingRegistrationRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/posts/new': typeof PostsNewRoute
  '/issues/': typeof IssuesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/issues/$issueId/comments': typeof IssuesIssueIdCommentsRoute
  '/issues/edit/$issueId': typeof IssuesEditIssueIdRoute
  '/issues/status/$issueId': typeof IssuesStatusIssueIdRoute
  '/posts/$postId/comments': typeof PostsPostIdCommentsRoute
  '/posts/edit/$postId': typeof PostsEditPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/settings': typeof SettingsRoute
  '/issues/new': typeof IssuesNewRoute
  '/onboarding/auth-method': typeof OnboardingAuthMethodRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/locked': typeof OnboardingLockedRoute
  '/onboarding/registration': typeof OnboardingRegistrationRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/posts/new': typeof PostsNewRoute
  '/issues': typeof IssuesIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/posts': typeof PostsIndexRoute
  '/issues/$issueId/comments': typeof IssuesIssueIdCommentsRoute
  '/issues/edit/$issueId': typeof IssuesEditIssueIdRoute
  '/issues/status/$issueId': typeof IssuesStatusIssueIdRoute
  '/posts/$postId/comments': typeof PostsPostIdCommentsRoute
  '/posts/edit/$postId': typeof PostsEditPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/issues': typeof IssuesRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/issues/new': typeof IssuesNewRoute
  '/onboarding/auth-method': typeof OnboardingAuthMethodRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/locked': typeof OnboardingLockedRoute
  '/onboarding/registration': typeof OnboardingRegistrationRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/posts/new': typeof PostsNewRoute
  '/issues/': typeof IssuesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/issues/$issueId/comments': typeof IssuesIssueIdCommentsRoute
  '/issues/edit/$issueId': typeof IssuesEditIssueIdRoute
  '/issues/status/$issueId': typeof IssuesStatusIssueIdRoute
  '/posts/$postId/comments': typeof PostsPostIdCommentsRoute
  '/posts/edit/$postId': typeof PostsEditPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/issues'
    | '/onboarding'
    | '/posts'
    | '/settings'
    | '/issues/new'
    | '/onboarding/auth-method'
    | '/onboarding/language'
    | '/onboarding/locked'
    | '/onboarding/registration'
    | '/onboarding/verification'
    | '/posts/new'
    | '/issues/'
    | '/onboarding/'
    | '/posts/'
    | '/issues/$issueId/comments'
    | '/issues/edit/$issueId'
    | '/issues/status/$issueId'
    | '/posts/$postId/comments'
    | '/posts/edit/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/settings'
    | '/issues/new'
    | '/onboarding/auth-method'
    | '/onboarding/language'
    | '/onboarding/locked'
    | '/onboarding/registration'
    | '/onboarding/verification'
    | '/posts/new'
    | '/issues'
    | '/onboarding'
    | '/posts'
    | '/issues/$issueId/comments'
    | '/issues/edit/$issueId'
    | '/issues/status/$issueId'
    | '/posts/$postId/comments'
    | '/posts/edit/$postId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/issues'
    | '/onboarding'
    | '/posts'
    | '/settings'
    | '/issues/new'
    | '/onboarding/auth-method'
    | '/onboarding/language'
    | '/onboarding/locked'
    | '/onboarding/registration'
    | '/onboarding/verification'
    | '/posts/new'
    | '/issues/'
    | '/onboarding/'
    | '/posts/'
    | '/issues/$issueId/comments'
    | '/issues/edit/$issueId'
    | '/issues/status/$issueId'
    | '/posts/$postId/comments'
    | '/posts/edit/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  IssuesRoute: typeof IssuesRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/issues/': {
      id: '/issues/'
      path: '/'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof PostsRoute
    }
    '/onboarding/verification': {
      id: '/onboarding/verification'
      path: '/verification'
      fullPath: '/onboarding/verification'
      preLoaderRoute: typeof OnboardingVerificationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/registration': {
      id: '/onboarding/registration'
      path: '/registration'
      fullPath: '/onboarding/registration'
      preLoaderRoute: typeof OnboardingRegistrationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/locked': {
      id: '/onboarding/locked'
      path: '/locked'
      fullPath: '/onboarding/locked'
      preLoaderRoute: typeof OnboardingLockedRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/language': {
      id: '/onboarding/language'
      path: '/language'
      fullPath: '/onboarding/language'
      preLoaderRoute: typeof OnboardingLanguageRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/auth-method': {
      id: '/onboarding/auth-method'
      path: '/auth-method'
      fullPath: '/onboarding/auth-method'
      preLoaderRoute: typeof OnboardingAuthMethodRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/issues/new': {
      id: '/issues/new'
      path: '/new'
      fullPath: '/issues/new'
      preLoaderRoute: typeof IssuesNewRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/posts/edit/$postId': {
      id: '/posts/edit/$postId'
      path: '/edit/$postId'
      fullPath: '/posts/edit/$postId'
      preLoaderRoute: typeof PostsEditPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/$postId/comments': {
      id: '/posts/$postId/comments'
      path: '/$postId/comments'
      fullPath: '/posts/$postId/comments'
      preLoaderRoute: typeof PostsPostIdCommentsRouteImport
      parentRoute: typeof PostsRoute
    }
    '/issues/status/$issueId': {
      id: '/issues/status/$issueId'
      path: '/status/$issueId'
      fullPath: '/issues/status/$issueId'
      preLoaderRoute: typeof IssuesStatusIssueIdRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/issues/edit/$issueId': {
      id: '/issues/edit/$issueId'
      path: '/edit/$issueId'
      fullPath: '/issues/edit/$issueId'
      preLoaderRoute: typeof IssuesEditIssueIdRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/issues/$issueId/comments': {
      id: '/issues/$issueId/comments'
      path: '/$issueId/comments'
      fullPath: '/issues/$issueId/comments'
      preLoaderRoute: typeof IssuesIssueIdCommentsRouteImport
      parentRoute: typeof IssuesRoute
    }
  }
}

interface IssuesRouteChildren {
  IssuesNewRoute: typeof IssuesNewRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  IssuesIssueIdCommentsRoute: typeof IssuesIssueIdCommentsRoute
  IssuesEditIssueIdRoute: typeof IssuesEditIssueIdRoute
  IssuesStatusIssueIdRoute: typeof IssuesStatusIssueIdRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesNewRoute: IssuesNewRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  IssuesIssueIdCommentsRoute: IssuesIssueIdCommentsRoute,
  IssuesEditIssueIdRoute: IssuesEditIssueIdRoute,
  IssuesStatusIssueIdRoute: IssuesStatusIssueIdRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

interface OnboardingRouteChildren {
  OnboardingAuthMethodRoute: typeof OnboardingAuthMethodRoute
  OnboardingLanguageRoute: typeof OnboardingLanguageRoute
  OnboardingLockedRoute: typeof OnboardingLockedRoute
  OnboardingRegistrationRoute: typeof OnboardingRegistrationRoute
  OnboardingVerificationRoute: typeof OnboardingVerificationRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAuthMethodRoute: OnboardingAuthMethodRoute,
  OnboardingLanguageRoute: OnboardingLanguageRoute,
  OnboardingLockedRoute: OnboardingLockedRoute,
  OnboardingRegistrationRoute: OnboardingRegistrationRoute,
  OnboardingVerificationRoute: OnboardingVerificationRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface PostsRouteChildren {
  PostsNewRoute: typeof PostsNewRoute
  PostsIndexRoute: typeof PostsIndexRoute
  PostsPostIdCommentsRoute: typeof PostsPostIdCommentsRoute
  PostsEditPostIdRoute: typeof PostsEditPostIdRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsNewRoute: PostsNewRoute,
  PostsIndexRoute: PostsIndexRoute,
  PostsPostIdCommentsRoute: PostsPostIdCommentsRoute,
  PostsEditPostIdRoute: PostsEditPostIdRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  IssuesRoute: IssuesRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
