export type IconGlyph =
  | 'arrow-right'
  | 'building-2'
  | 'camera'
  | 'check'
  | 'chevron-right'
  | 'clipboard-check'
  | 'door-closed'
  | 'droplet-off'
  | 'list-checks'
  | 'loader-circle'
  | 'map-pin'
  | 'megaphone'
  | 'message-circle'
  | 'phone'
  | 'shield-check'
  | 'user'
  | 'zap'
